name: flutter_nerolab_cli
description: Command Line Interface to generate flutter starter project.
homepage: https://nerolab.dev/
repository: https://github.com/Nerolab/nerolab_cli
version: 0.1.2

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.3.0
  io: ^1.0.3
  mason: ^0.1.0-dev.2
  meta: ^1.7.0
  path: ^1.8.1
  usage: ^4.0.2

dev_dependencies:
  build_runner: ^2.1.7
  build_verify: ^3.0.0
  build_version: ^2.1.0
  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  test: ^1.20.1

executables:
  nerolab:
